-- auto-generated definition
create table realty_contract
(
    rc_seq                         bigint auto_increment comment 'Realty Contract 시퀀스'
        primary key,
    c_seq                          bigint                                    not null comment 'Realty Contract 계약서 최초 작성 회원 시퀀스',
    rc_contract_type               varchar(10)                               not null comment 'Realty Contract 계약 유형
sale: 매매
jeonse: 전세
monthly: 월세',
    rc_customer_type               varchar(10)                               not null comment 'Realty Contract 계약서 최초 작성 회원 유형',
    rc_road_address                varchar(500)                              not null comment 'Realty Contract 계약목적물 도로명 주소',
    rc_jibun_address               varchar(500)                              not null comment 'Realty Contract 계약목적물 지번주소',
    rc_detail_address              varchar(500)                              not null comment 'Realty Contract 상세주소',
    rc_postcode                    varchar(10)                               not null comment 'Realty Contract 우편번호',
    rc_bulding_area                decimal(7, 2) default 0.00                not null comment 'Realty Contract 건물 면적',
    rc_dong                        varchar(10)   default '0'                 null comment 'Realty Contract 계약목적물 동수',
    rc_floor                       tinyint       default 0                   null comment 'Realty Contract 계약목적물 층수',
    rc_ho                          varchar(10)   default '0'                 null comment 'Realty Contract 계약목적물 호수',
    rc_area                        decimal(6, 2) default 0.00                not null comment 'Realty Contract 전용면적 (임차할부분)',
    rc_land_type                   varchar(5)                                not null comment 'Realty Contract 토지 지목(지목코드 파일 생성예정)',
    rc_land_area                   decimal(7, 2) default 0.00                not null comment 'Realty Contract 토지 면적',
    rc_building_structure          varchar(5)                                not null comment 'Realty Contract 건물 구조 (건물구조코드 파일 생성예정)',
    rc_building_type               varchar(10)                               not null comment 'Realty Contract 건물 유형 (건물유형코드 파일 생성예정)',
    rc_contract_is_new             tinyint(1)    default 1                   not null comment 'Realty Contract 신규 계약 여부
0: 재계약
1: 신규 계약',
    rc_before_document_seq         bigint                                    null comment 'Realty Contract 재계약인 경우 이전 계약서 시퀀스',
    c_seq_lessor                   bigint                                    null comment 'Realty Contract 임대인 회원 시퀀스',
    rc_lessor_road_address         varchar(500)                              not null comment 'Realty Contract 임대인 도로명주소*암호화',
    rc_lessor_jibun_address        varchar(500)                              not null comment 'Realty Contract 임대인 지번주소*암호화',
    rc_lessor_detail_address       varchar(500)                              not null comment 'Realty Contract 임대인 상세주소*암호화',
    rc_lessor_postcode             varchar(10)                               not null comment 'Realty Contract 임대인 우편번호',
    rc_lessor_name                 varchar(100)                              not null comment 'Realty Contract 임대인 성명*암호화',
    rc_lessor_rrn_front            char(6)                                   not null comment 'Realty Contract 임대인 주민번호 앞자리',
    rc_lessor_rrn_back             varchar(100)                              not null comment 'Realty Contract 주민번호 뒷자리 *암호화',
    rc_lessor_phone                varchar(100)                              not null comment 'Realty Contract 임대인 핸드폰번호 *암호화',
    rc_lessor_agent_name           varchar(100)                              not null comment 'Realty Contract 임대 대리인 성명*암호화',
    rc_lessor_agent_rrn_front      char(6)                                   not null comment 'Realty Contract 임대 대리인 주민번호 앞자리',
    rc_lessor_agent_rrn_back       varchar(100)                              not null comment 'Realty Contract 임대 대리인 주민번호 뒷자리*암호화',
    rc_lessor_agent_road_address   varchar(500)                              not null comment 'Realty Contract 임대 대리인 도로명주소*암호화',
    rc_lessor_agent_jibun_address  varchar(500)                              not null comment 'Realty Contract 임대 대리인 지번주소*암호화',
    rc_lessor_agent_detail_address varchar(500)                              not null comment 'Realty Contract 임대 대리인 상세주소*암호화',
    rc_lessor_agent_postcode       varchar(10)                               null comment 'Realty Contract 임대 대리인 우편번호',
    c_seq_lessee                   bigint                                    null comment 'Realty Contract 임차인 회원 시퀀스',
    rc_lessee_name                 varchar(100)                              not null comment 'Realty Contract 임차인 성명*암호화',
    rc_lessee_rrn_front            char(6)                                   not null comment 'Realty Contract 임차인 주민번호 앞자리',
    rc_lessee_rrn_back             varchar(100)                              not null comment 'Realty Contract 임차인 주민번호 뒷자리*암호화',
    rc_lessee_phone                varchar(100)                              not null comment 'Realty Contract 임차인 핸드폰번호*암호화',
    rc_lessee_road_address         varchar(500)                              not null comment 'Realty Contract 임차인 도로명주소*암호화',
    rc_lessee_jibun_address        varchar(500)                              not null comment 'Realty Contract 임차인 지번주소*암호화',
    rc_lessee_detail_address       varchar(500)                              not null comment 'Realty Contract 임차인 상세주소*암호화',
    rc_lessee_postcode             varchar(10)                               not null comment 'Realty Contract 임차인 우편번호',
    rc_lessee_agent_name           varchar(100)                              not null comment 'Realty Contract 임차 대리인 성명*암호화',
    rc_lessee_agent_rrn_front      char(6)                                   not null comment 'Realty Contract 임차 대리인 주민번호 앞자리',
    rc_lessee_agent_rrn_back       varchar(100)                              not null comment 'Realty Contract 임차 대리인 주민번호 뒷자리*암호화',
    rc_lessee_agent_road_address   varchar(500)                              not null comment 'Realty Contract 임차 대리인 도로명 주소*암호화',
    rc_lessee_agent_jibun_address  varchar(500)                              not null comment 'Realty Contract 임차 대리인 지번주소*암호화',
    rc_lessee_agent_detail_address varchar(500)                              not null comment 'Realty Contract 임차 대리인 상세주소*암호화',
    rc_lessee_agent_postcode       varchar(10)                               not null comment 'Realty Contract 임차 대리인 우편번호',
    c_seq_agent                    bigint                                    null comment 'Realty Contract 중개인 회원 시퀀스',
    rc_agency_road_address         varchar(100)                              not null comment 'Realty Contract 공인중개소 도로명 주소',
    rc_agency_jibun_address        varchar(100)                              null comment 'Realty Contract 공인중개소 지번 주소(없을수있음)',
    rc_agency_detail_address       varchar(100)                              null comment 'Realty Contract 공인중개소 상세 주소(없을수있음)',
    rc_agency_postcode             varchar(10)                               null comment 'Realty Contract 공인중개소 우편번호(없을수있음)',
    rc_agency_name                 varchar(50)                               not null comment 'Realty Contract 공인중개소 사무소명칭',
    rc_agency_owner                varchar(50)                               not null comment 'Realty Contract 공인중개소 대표 명',
    rc_agency_registration_number  varchar(50)                               not null comment 'Realty Contract 공인중개소 등록번호',
    rc_agency_phone                varchar(20)                               not null comment 'Realty Contract 공인중개소 전화번호',
    rc_agency_agent_name           varchar(50)                               not null comment 'Realty Contract 공인중개소 소속공인중개사 성명',
    rc_contract_start_date         datetime                                  not null comment 'Realty Contract 계약 시작 일시',
    rc_contract_end_date           datetime                                  not null comment 'Realty Contract 계약 종료 일시',
    rc_deposit                     int           default 0                   not null comment 'Realty Contract 보증금',
    rc_rent                        int           default 0                   not null comment 'Realty Contract 월세',
    rc_rent_pay_day                tinyint       default 1                   not null comment 'Realty Contract 월세 입금일, 날짜 (1~31)',
    rc_bank                        varchar(3)                                not null comment 'Realty Contract 월세 입금 계좌 - 은행 (은행코드 파일 생성예정)',
    rc_bank_account_number         varchar(50)                               not null comment 'Realty Contract 월세 입금 계좌 번호',
    rc_maintenance_is_fixed        tinyint(1)                                not null comment 'Realty Contract 관리비 고정 여부
0: 가변
1: 고정',
    rc_maintenance_fee             varchar(500)  default '0'                 not null comment 'Realty Contract 관리비, 고정일 경우 Number치환 필요',
    rc_down_payment                int           default 0                   not null comment 'Realty Contract 계약금',
    rc_middle_payment              int           default 0                   not null comment 'Realty Contract 중도금',
    rc_middle_payment_date         datetime                                  null comment 'Realty Contract 중도금지불일',
    rc_balance                     int           default 0                   not null comment 'Realty Contract 잔금',
    rc_balance_date                datetime                                  not null comment 'Realty Contract 잔금지불일',
    rc_parking_yn                  tinyint(1)    default 0                   not null comment 'Realty Contract 주차가능여부
0: 불가능
1: 가능',
    rc_parking_fee                 int           default 0                   not null comment 'Realty Contract 주차비',
    rc_special_terms_ids           varchar(500)                              not null comment 'Realty Contract 특약사항 (특약사항 테이블시퀀스, 구분자는 콤마)',
    rc_contract_issue_date         datetime      default current_timestamp() not null comment 'Realty Contract 계약서 교부일 (작성완료 시점)',
    rc_agency_owner_signature      varchar(500)                              not null comment 'Realty Contract 공인중개소 대표 서명(이미지 공통 테이블에서)',
    rc_lessor_signed_date          datetime                                  null comment 'Realty Contract 임대인 서명완료 일시',
    rc_lessor_signature            varchar(500)                              null comment 'Realty Contract 임대인 서명(이미지 공통 테이블에서)',
    rc_lessee_signed_date          datetime                                  null comment 'Realty Contract 임차인 서명완료 일시',
    rc_lessee_signature            varchar(500)                              null comment 'Realty Contract 임차인 서명(이미지 공통 테이블에서)',
    rc_agent_signed_date           datetime                                  null comment 'Realty Contract 중개인 서명완료 일시',
    rc_agent_signature             varchar(500)                              null comment 'Realty Contract 중개인 서명(이미지 공통 테이블에서)',
    rc_updated                     datetime      default current_timestamp() not null comment 'Realty Contract 수정일자',
    rc_created                     datetime      default current_timestamp() not null comment 'Realty Contract 생성일자',
    rc_contract_effective_date     datetime                                  null comment 'Realty Contract 계약 성립일(임대인/임차인/중개인 모두 서명 완료된 날짜)',
    constraint realty_contract_rc_seq_uindex
        unique (rc_seq)
)
    comment '부동산 전자계약서' collate = utf8mb4_unicode_ci;

