from django.db import models

class RealtyContract(models.Model):
    rc_seq = models.BigAutoField(primary_key=True, db_comment='Realty Contract 시퀀스')
    c_seq = models.BigIntegerField(db_comment='Realty Contract 계약서 최초 작성 회원 시퀀스')
    rc_contract_type = models.CharField(max_length=10, db_comment='Realty Contract 계약 유형\nsale: 매매\njeonse: 전세\nmonthly: 월세')
    rc_customer_type = models.CharField(max_length=10, db_comment='Realty Contract 계약서 최초 작성 회원 유형')
    rc_road_address = models.CharField(max_length=500, db_comment='Realty Contract 계약목적물 도로명 주소')
    rc_jibun_address = models.CharField(max_length=500, db_comment='Realty Contract 계약목적물 지번주소')
    rc_detail_address = models.CharField(max_length=500, db_comment='Realty Contract 상세주소')
    rc_postcode = models.CharField(max_length=10, db_comment='Realty Contract 우편번호')
    rc_bulding_area = models.DecimalField(max_digits=7, decimal_places=2, db_comment='Realty Contract 건물 면적')
    rc_dong = models.CharField(max_length=10, blank=True, null=True, db_comment='Realty Contract 계약목적물 동수')
    rc_floor = models.IntegerField(blank=True, null=True, db_comment='Realty Contract 계약목적물 층수')
    rc_ho = models.CharField(max_length=10, blank=True, null=True, db_comment='Realty Contract 계약목적물 호수')
    rc_area = models.DecimalField(max_digits=6, decimal_places=2, db_comment='Realty Contract 전용면적 (임차할부분)')
    rc_land_type = models.CharField(max_length=5, db_comment='Realty Contract 토지 지목(지목코드 파일 생성예정)')
    rc_land_area = models.DecimalField(max_digits=7, decimal_places=2, db_comment='Realty Contract 토지 면적')
    rc_building_structure = models.CharField(max_length=5, db_comment='Realty Contract 건물 구조 (건물구조코드 파일 생성예정)')
    rc_building_type = models.CharField(max_length=10, db_comment='Realty Contract 건물 유형 (건물유형코드 파일 생성예정)')
    rc_contract_is_new = models.IntegerField(db_comment='Realty Contract 신규 계약 여부\n0: 재계약\n1: 신규 계약')
    rc_before_document_seq = models.BigIntegerField(blank=True, null=True, db_comment='Realty Contract 재계약인 경우 이전 계약서 시퀀스')
    c_seq_lessor = models.BigIntegerField(blank=True, null=True, db_comment='Realty Contract 임대인 회원 시퀀스')
    rc_lessor_road_address = models.CharField(max_length=500, db_comment='Realty Contract 임대인 도로명주소*암호화')
    rc_lessor_jibun_address = models.CharField(max_length=500, db_comment='Realty Contract 임대인 지번주소*암호화')
    rc_lessor_detail_address = models.CharField(max_length=500, db_comment='Realty Contract 임대인 상세주소*암호화')
    rc_lessor_postcode = models.CharField(max_length=10, db_comment='Realty Contract 임대인 우편번호')
    rc_lessor_name = models.CharField(max_length=100, db_comment='Realty Contract 임대인 성명*암호화')
    rc_lessor_rrn_front = models.CharField(max_length=6, db_comment='Realty Contract 임대인 주민번호 앞자리')
    rc_lessor_rrn_back = models.CharField(max_length=100, db_comment='Realty Contract 주민번호 뒷자리 *암호화')
    rc_lessor_phone = models.CharField(max_length=100, db_comment='Realty Contract 임대인 핸드폰번호 *암호화')
    rc_lessor_agent_name = models.CharField(max_length=100, db_comment='Realty Contract 임대 대리인 성명*암호화')
    rc_lessor_agent_rrn_front = models.CharField(max_length=6, db_comment='Realty Contract 임대 대리인 주민번호 앞자리')
    rc_lessor_agent_rrn_back = models.CharField(max_length=100, db_comment='Realty Contract 임대 대리인 주민번호 뒷자리*암호화')
    rc_lessor_agent_road_address = models.CharField(max_length=500, db_comment='Realty Contract 임대 대리인 도로명주소*암호화')
    rc_lessor_agent_jibun_address = models.CharField(max_length=500, db_comment='Realty Contract 임대 대리인 지번주소*암호화')
    rc_lessor_agent_detail_address = models.CharField(max_length=500, db_comment='Realty Contract 임대 대리인 상세주소*암호화')
    rc_lessor_agent_postcode = models.CharField(max_length=10, blank=True, null=True, db_comment='Realty Contract 임대 대리인 우편번호')
    c_seq_lessee = models.BigIntegerField(blank=True, null=True, db_comment='Realty Contract 임차인 회원 시퀀스')
    rc_lessee_name = models.CharField(max_length=100, db_comment='Realty Contract 임차인 성명*암호화')
    rc_lessee_rrn_front = models.CharField(max_length=6, db_comment='Realty Contract 임차인 주민번호 앞자리')
    rc_lessee_rrn_back = models.CharField(max_length=100, db_comment='Realty Contract 임차인 주민번호 뒷자리*암호화')
    rc_lessee_phone = models.CharField(max_length=100, db_comment='Realty Contract 임차인 핸드폰번호*암호화')
    rc_lessee_road_address = models.CharField(max_length=500, db_comment='Realty Contract 임차인 도로명주소*암호화')
    rc_lessee_jibun_address = models.CharField(max_length=500, db_comment='Realty Contract 임차인 지번주소*암호화')
    rc_lessee_detail_address = models.CharField(max_length=500, db_comment='Realty Contract 임차인 상세주소*암호화')
    rc_lessee_postcode = models.CharField(max_length=10, db_comment='Realty Contract 임차인 우편번호')
    rc_lessee_agent_name = models.CharField(max_length=100, db_comment='Realty Contract 임차 대리인 성명*암호화')
    rc_lessee_agent_rrn_front = models.CharField(max_length=6, db_comment='Realty Contract 임차 대리인 주민번호 앞자리')
    rc_lessee_agent_rrn_back = models.CharField(max_length=100, db_comment='Realty Contract 임차 대리인 주민번호 뒷자리*암호화')
    rc_lessee_agent_road_address = models.CharField(max_length=500, db_comment='Realty Contract 임차 대리인 도로명 주소*암호화')
    rc_lessee_agent_jibun_address = models.CharField(max_length=500, db_comment='Realty Contract 임차 대리인 지번주소*암호화')
    rc_lessee_agent_detail_address = models.CharField(max_length=500, db_comment='Realty Contract 임차 대리인 상세주소*암호화')
    rc_lessee_agent_postcode = models.CharField(max_length=10, db_comment='Realty Contract 임차 대리인 우편번호')
    c_seq_agent = models.BigIntegerField(blank=True, null=True, db_comment='Realty Contract 중개인 회원 시퀀스')
    rc_agency_road_address = models.CharField(max_length=100, db_comment='Realty Contract 공인중개소 도로명 주소')
    rc_agency_jibun_address = models.CharField(max_length=100, blank=True, null=True, db_comment='Realty Contract 공인중개소 지번 주소(없을수있음)')
    rc_agency_detail_address = models.CharField(max_length=100, blank=True, null=True, db_comment='Realty Contract 공인중개소 상세 주소(없을수있음)')
    rc_agency_postcode = models.CharField(max_length=10, blank=True, null=True, db_comment='Realty Contract 공인중개소 우편번호(없을수있음)')
    rc_agency_name = models.CharField(max_length=50, db_comment='Realty Contract 공인중개소 사무소명칭')
    rc_agency_owner = models.CharField(max_length=50, db_comment='Realty Contract 공인중개소 대표 명')
    rc_agency_registration_number = models.CharField(max_length=50, db_comment='Realty Contract 공인중개소 등록번호')
    rc_agency_phone = models.CharField(max_length=20, db_comment='Realty Contract 공인중개소 전화번호')
    rc_agency_agent_name = models.CharField(max_length=50, db_comment='Realty Contract 공인중개소 소속공인중개사 성명')
    rc_contract_start_date = models.DateTimeField(db_comment='Realty Contract 계약 시작 일시')
    rc_contract_end_date = models.DateTimeField(db_comment='Realty Contract 계약 종료 일시')
    rc_deposit = models.IntegerField(db_comment='Realty Contract 보증금')
    rc_rent = models.IntegerField(db_comment='Realty Contract 월세')
    rc_rent_pay_day = models.IntegerField(db_comment='Realty Contract 월세 입금일, 날짜 (1~31)')
    rc_bank = models.CharField(max_length=3, db_comment='Realty Contract 월세 입금 계좌 - 은행 (은행코드 파일 생성예정)')
    rc_bank_account_number = models.CharField(max_length=50, db_comment='Realty Contract 월세 입금 계좌 번호')
    rc_maintenance_is_fixed = models.IntegerField(db_comment='Realty Contract 관리비 고정 여부\n0: 가변\n1: 고정')
    rc_maintenance_fee = models.CharField(max_length=500, db_comment='Realty Contract 관리비, 고정일 경우 Number치환 필요')
    rc_down_payment = models.IntegerField(db_comment='Realty Contract 계약금')
    rc_middle_payment = models.IntegerField(db_comment='Realty Contract 중도금')
    rc_middle_payment_date = models.DateTimeField(blank=True, null=True, db_comment='Realty Contract 중도금지불일')
    rc_balance = models.IntegerField(db_comment='Realty Contract 잔금')
    rc_balance_date = models.DateTimeField(db_comment='Realty Contract 잔금지불일')
    rc_parking_yn = models.IntegerField(db_comment='Realty Contract 주차가능여부\n0: 불가능\n1: 가능')
    rc_parking_fee = models.IntegerField(db_comment='Realty Contract 주차비')
    rc_special_terms_ids = models.CharField(max_length=500, db_comment='Realty Contract 특약사항 (특약사항 테이블시퀀스, 구분자는 콤마)')
    rc_contract_issue_date = models.DateTimeField(db_comment='Realty Contract 계약서 교부일 (작성완료 시점)')
    rc_agency_owner_signature = models.CharField(max_length=500, db_comment='Realty Contract 공인중개소 대표 서명(이미지 공통 테이블에서)')
    rc_lessor_signed_date = models.DateTimeField(blank=True, null=True, db_comment='Realty Contract 임대인 서명완료 일시')
    rc_lessor_signature = models.CharField(max_length=500, blank=True, null=True, db_comment='Realty Contract 임대인 서명(이미지 공통 테이블에서)')
    rc_lessee_signed_date = models.DateTimeField(blank=True, null=True, db_comment='Realty Contract 임차인 서명완료 일시')
    rc_lessee_signature = models.CharField(max_length=500, blank=True, null=True, db_comment='Realty Contract 임차인 서명(이미지 공통 테이블에서)')
    rc_agent_signed_date = models.DateTimeField(blank=True, null=True, db_comment='Realty Contract 중개인 서명완료 일시')
    rc_agent_signature = models.CharField(max_length=500, blank=True, null=True, db_comment='Realty Contract 중개인 서명(이미지 공통 테이블에서)')
    rc_updated = models.DateTimeField(db_comment='Realty Contract 수정일자')
    rc_created = models.DateTimeField(db_comment='Realty Contract 생성일자')
    rc_contract_effective_date = models.DateTimeField(blank=True, null=True, db_comment='Realty Contract 계약 성립일(임대인/임차인/중개인 모두 서명 완료된 날짜)')

    class Meta:
        managed = False
        db_table = 'realty_contract'
        db_table_comment = '부동산 전자계약서'
